# Generated by Django 4.2.11 on 2024-04-02 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('I', 'JPO I'), ('II', 'JPO II'), ('III', 'JPO III'), ('IV', 'JPO IV'), ('V', 'JPO V'), ('VI', 'JPO VI')], max_length=10)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Jednotka',
                'verbose_name_plural': 'Jednotky',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('H', 'Hasič'), ('SH', 'Starší hasič'), ('S', 'Strojník'), ('T', 'Technik'), ('VD', 'Velitel družstva'), ('ZVJ', 'Zástupce velitele jednotky'), ('VJ', 'Velitel jednotky')], max_length=10)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Responder.unit')),
            ],
            options={
                'verbose_name': 'Člen',
                'verbose_name_plural': 'Členové',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('licence_plate', models.CharField(max_length=10)),
                ('call_sign', models.CharField(max_length=10)),
                ('mark', models.CharField(max_length=5)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Responder.unit')),
            ],
            options={
                'verbose_name': 'Technika',
                'verbose_name_plural': 'Technika',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('AG', 'Agregát'), ('PR', 'Přilba'), ('KB', 'Kabát'), ('KA', 'Kalhoty'), ('BT', 'Boty'), ('KU', 'Kukla'), ('IDP', 'Dýchycí přístroj'), ('OP', 'Ostatní vybavení')], max_length=10)),
                ('equipment_name', models.CharField(max_length=40)),
                ('equipment_date', models.DateField(default=datetime.date.today)),
                ('machinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Responder.machinery')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Responder.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Responder.unit')),
            ],
            options={
                'verbose_name': 'Vybavení',
                'verbose_name_plural': 'Vybavení',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_type', models.CharField(choices=[('P', 'Požár'), ('TP', 'Technická pomoc'), ('DN', 'Dopravní nehoda'), ('ZOZ', 'Záchrana osob a zvířat'), ('UNL', 'Únik nebezpečných látek')], max_length=10)),
                ('inc_subtype', models.CharField(choices=[('NB', 'Nízké budovy'), ('VB', 'Výškové budovy'), ('DP', 'Dopravní prostředek'), ('Strom', 'Odstranění stromu'), ('Hmyz', 'Likvidace hmyzu'), ('Cerpani', 'Čerpání vody'), ('Vzduch', 'Do ovzduší'), ('Voda', 'Do vody'), ('Puda', 'Do půdy'), ('Prostor', 'Uzavřený prostor'), ('Trava', 'Polní porost, tráva')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('place_desc', models.CharField(max_length=50)),
                ('inc_desc', models.CharField(max_length=50)),
                ('inc_level', models.IntegerField(default=1)),
                ('members', models.ManyToManyField(blank=True, to='Responder.member')),
                ('trucks', models.ManyToManyField(blank=True, to='Responder.machinery')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Responder.unit')),
            ],
        ),
    ]
