# Generated by Django 4.2.11 on 2024-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Responder', '0002_unit_latitude_unit_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='static/images/firefighter.jpg', upload_to=''),
        ),
    ]
