# Generated by Django 4.2.11 on 2024-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Responder', '0003_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='image',
            field=models.ImageField(blank=True, default='static/images/firetruck.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('JD', 'Jedu'), ('NJ', 'Nejedu'), ('NZ', 'Neznamo')], default='NZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='static/images/firefighter.jpg', null=True, upload_to='images/'),
        ),
    ]
