# Generated by Django 4.2.11 on 2024-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Responder', '0004_equipment_image_machinery_image_member_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
