# Generated by Django 4.2.11 on 2024-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Responder', '0005_call_latitude_call_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
