# Generated by Django 4.2.11 on 2024-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Responder', '0006_call_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='minutes_to_answer',
            field=models.IntegerField(default=2),
        ),
    ]
